grafana/metrics-drilldown

src/MetricSelect/AddToExplorationsButton.test.tsx, src/MetricSelect/AddToExplorationsButton.tsx, src/plugin.json
https://github.com/grafana/investigations-app/pull/175
=> feat(explorations): change to new plugin id

.github/workflows/bundle-stats-compare.yml, .github/workflows/ci.yml
This PR will allow us to create plugin artifacts on-demand.
=> ci: enable workflow dispatch for CI

src/WingmanDataTrail/MetricsReducer.tsx
https://github.com/user-attachments/assets/68a8606f-6b54-40dd-ae02-c9ae5e5dd69e
=> Style: Fix sidebar UI

src/DataTrail.tsx, src/WingmanDataTrail/HeaderControls/HeaderControls.tsx, src/WingmanDataTrail/MetricVizPanel/MetricVizPanel.tsx, src/WingmanDataTrail/MetricVizPanel/MetricsVariable.ts, src/WingmanDataTrail/MetricVizPanel/SimpleMetricsList.tsx, src/WingmanDataTrail/MetricVizPanel/buildPrometheusQuery.ts, src/WingmanDataTrail/MetricVizPanel/getPrometheusMetricType.ts, src/WingmanDataTrail/MetricsReducer.tsx
Adding real data + toggle between the "group by" list and simple one:
https://github.com/user-attachments/assets/0a9303aa-a554-47f2-9f84-f650a1d4c4ae
=> feat(WingmanHackathon): Add simple list with metrics and group by toggle

src/WingmanDataTrail/MetricsReducer.tsx
**changes:**
**pre changes**
**post changes**
=> Style: Sidebar UI refinements

src/WingmanDataTrail/HeaderControls/GroupByControls.tsx, src/WingmanDataTrail/HeaderControls/HeaderControls.tsx, src/WingmanDataTrail/MetricsGroupByList.tsx, src/WingmanDataTrail/MetricsReducer.tsx
This PR updates `groupBy` to be a Scenes variable. This allows us to subscribe to variable changes for more reliable updates.
https://github.com/user-attachments/assets/afab5cd1-7c7a-4475-a5ab-3b7a1040f527
=> Hackathon: Refactor groupBy as a scenes variable

src/App/Routes.tsx, src/WingmanOnboarding/HeaderControls/MainLabelVariable.tsx, src/WingmanOnboarding/MetricsOnboarding.tsx, src/constants.ts, src/pages/OnboardWingman.tsx
https://github.com/user-attachments/assets/c3fc1ab6-0ed3-4706-b6a1-478a3aa16553
- Go to the new URL: http://localhost:3001/a/grafana-metricsdrilldown-app/onboard-wingman
=> feat(WingmanHackathon): Onboarding view

.github/CODEOWNERS
adds a codeownders file to the repo
=> chore: adds codeowners for CVE tool

src/WingmanDataTrail/GroupBy/MetricsGroupByRow.tsx
Next steps: get exclude button to work!
=> Smooth pagination and styles update

src/DataTrail.tsx, src/WingmanDataTrail/GroupBy/MetricsGroupByList.tsx, src/WingmanDataTrail/GroupBy/MetricsGroupByRow.tsx, src/WingmanDataTrail/HeaderControls/QuickSearch.tsx, src/WingmanDataTrail/Labels/LabelsVariable.tsx, src/WingmanDataTrail/MetricVizPanel/MetricVizPanel.tsx, src/WingmanDataTrail/MetricVizPanel/buildPrometheusQuery.ts, src/WingmanDataTrail/MetricsList/SimpleMetricsList.tsx, src/WingmanDataTrail/MetricsVariables/FilteredMetricsVariable.ts, src/WingmanDataTrail/MetricsVariables/MetricsVariable.ts, src/WingmanDataTrail/MetricsVariables/categoryMatchers.ts, src/WingmanDataTrail/MetricsVariables/computeMetricCategories.ts, src/WingmanDataTrail/MetricsVariables/computeMetricPrefixGroups.ts, src/WingmanDataTrail/SideBar/MetricsFilterSection.tsx, src/WingmanDataTrail/SideBar/SideBar.tsx
Add filtering capabilities (quick search and side bar filters):
https://github.com/user-attachments/assets/bd7cf07a-8884-48cf-b11c-2327be1fe54d
In a future PR, we'll make the counts update in the side bar.
=> feat(WingmanHackathon): Implement filtering (with count updates)

README.md, src/README.md, src/plugin.json
👋 After the discussion, we are updating description to match the documentation https://grafana.com/docs/grafana/latest/explore/simplified-exploration/
=> Update app description

src/WingmanDataTrail/Labels/LabelsDataSource.ts
What happened? Sometimes the label group by options don't load and you see that the drop down only included the `none` option.
Why?
This bug occurs when a DS does not support the labels match[] parameter.
If a Prometheus DS does not support the labels match[] api, we must use the series endpoint instead. But, the series endpoint rejects empty matchers.
`"{__name__=~".+",$filters}"` is evaluated as empty.
So, we can use `getTagKeys` which is used in adhocVariables and will handle the empty matcher for the series endpoint. 
How to test:
1. Create a data source that does not support the labels match api.
2. You can do this by explicitly setting the data source to use the series endpoint
3. Next, start wingman using that data source.
4. See that the label group options load.
Future work for …
=> handle series endpoint bug with empty matcher

CHANGELOG.md
This PR adds the release notes from the most recent release to the changelog.
=> docs: add link to latest release notes

src/WingmanDataTrail/MetricVizPanel/MetricVizPanel.tsx, src/autoQuery/units.ts
Reverts grafana/metrics-drilldown#197
=> Revert "fix: display unit in metric panel y-axis"

.github/workflows/ci.yml, .github/workflows/playwright-published.yml
Run e2e tests against each commit to `main`
=> chore: e2e to run against main

.github/workflows/playwright-published.yml
...and we want to upload artifacts
=> fix: specify branch on e2e-workflow

src/version.ts
This PR undoes a change made in error in #223.
=> chore: fix erroneous change

src/Breakdown/SortByScene.tsx, src/BreakdownLabelSelector.tsx, src/MetricSelect/MetricSelectScene.tsx
Kept noticing the linter was always complaining about this, so lets see how cursor did
=> chore: update deprecated Select to Combobox

CHANGELOG.md, package-lock.json, package.json
This PR prepares the `v1.0.0-7` prerelease.
=> chore: prerelease v1.0.0-7

CHANGELOG.md, package-lock.json, package.json
This PR prepares the `v1.0.0-8` prerelease.
=> chore: prerelease v1.0.0-8

.github/workflows/bundle-stats-compare.yml, .github/workflows/bundle-stats-create.yml, .github/workflows/ci.yml, .github/workflows/cp-update.yml, .github/workflows/is-compatible.yml, .github/workflows/playwright-published.yml, .github/workflows/publish.yml
This PR fixes the hashes used to pin remote actions in #360.
I ran https://github.com/grafana/github-action-patcher and committed the updates.
=> ci: fix action pins

src/WingmanDataTrail/SideBar/SideBar.tsx
|  https://github.com/user-attachments/assets/55606449-8dda-440a-b89c-63c0f3882174|  https://github.com/user-attachments/assets/76b1aaa4-7b35-4758-953a-0c1e55d5298e|
See diff tab
- Go to the Metrics Reducer view
- Add some prefix/suffix filters
- The read-only filters input should appear next to the ad hoc filters
- Select a metric panel
- The read-only filters input should not appear
=> fix(MetricScene): Hide prefix/suffix filters

package-lock.json, package.json
a wonderful effect of this is fixing the bug where `showMenuAlways` wasn't correctly making the menu show w/o hover
fixes https://github.com/grafana/metrics-drilldown/issues/358
=> Chore: Upgrade Scenes

CHANGELOG.md, package-lock.json, package.json
This PR bumps the version for the final prerelease of version 1 (`1.0.0-9`).
=> chore: prerelease v1.0.0-9

.github/workflows/ci.yml, .github/workflows/playwright-published.yml, .github/workflows/publish-technical-documentation-next.yml
Narrow down the permissions from the whole workflow to just the step that needs it
=> fix: playright published broad permissions

docs/sources/_index.md
This PR adds the metrics drilldown learning journey to the docs
=> docs: add metrics drilldown learning journey

CHANGELOG.md, package-lock.json, package.json
This PR bumps the version for the first prerelease of version 1.0.2 (1.0.2-0).
`-`
`-`
=> chore: prerelease v1.0.2-0

README.md
This PR adds the link to our (complete) E2E testing documentation.
See diff tab
`-`
=> docs(README): Add link to our E2E testing doc

src/App/useReportAppInitialized.ts
**Related issue(s):** is a followup of https://github.com/grafana/metrics-drilldown/pull/463
See diff tab
`-`
=> perf: Improve performance when tracking app init event

CHANGELOG.md, package-lock.json, package.json
=> Bump version v1.0.3

jest.config.js, package-lock.json, src/helpers/MetricDatasourceHelper.ts, src/mocks/datasource.ts
Runs `npm update` to fix low vulnerability CVE from `brace-expansion` indirect dependency
=> fix: CVE-2025-5889

e2e/docker/Dockerfile.playwright, package-lock.json, package.json
Update Playwright to [v1.55.0](https://playwright.dev/docs/release-notes#version-155)
`-`
The build should pass
=> chore: Update Playwright to v1.55.0

src/helpers/MetricDatasourceHelper.spec.ts, src/helpers/MetricDatasourceHelper.ts, src/mocks/datasource.ts
**Related issue(s):** follow-up of https://github.com/grafana/metrics-drilldown/pull/647
Just a follow-up of the linked PR to add some unit tests and slightly improve the performance of the detection flow.
See diff tab
=> refactor(NativeHistograms): Slight improvement and unit tests

src/WingmanDataTrail/ListControls/LayoutSwitcher.tsx, src/interactions.ts
A small PR to track the changes of layout:
See diff tab
=> chore(LayoutSwitcher): Track layout changes

e2e/fixtures/views/MetricSceneView.ts, e2e/tests/metric-scene-view.spec.ts, src/Menu/PanelMenu.tsx, src/MetricGraphScene.tsx
**Related issue(s):** https://github.com/grafana/metrics-drilldown/issues/711
Adds e2e test for panel menu items
Build should pass
=> test: e2e test for panel menu

package-lock.json
https://github.com/grafana/scenes/releases/tag/v6.39.0
`-`
=> chore(Scenes): Upgrade Scenes to v6.39.0

package-lock.json, package.json
This PR upgrades `@grafana/scenes` to take advantage of https://github.com/grafana/scenes/pull/1250, which makes custom values appear first in the filters combobox. This is provides nice UX, especially for people using regex in label values.
Upgrades `@grafana/scenes` to the `@latest` version.
The CI should pass.
=> feat: custom values appear first in label filters
