grafana/metrics-drilldown

- .github/workflows/ci.yml
This PR allows us to use `main` again now that https://github.com/grafana/plugin-ci-workflows/pull/41 has been merged.
> fix: use `main` again now that it's been fixed

- .gitignore
This PR is a quality-of-life update. It allows us to provision datasources via a `provisioning/datasources/local.yaml` file (note: it doesn't need to be called `local`) without fear of committing any `secureJsonData[basicAuthPassword]`s to this repo.
> chore: exclude non-default provisioned plugins from source control

- README.md
- src/Integrations/dashboardIntegration.ts
- src/MetricSelect/AddToExplorationsButton.tsx
- src/MetricSelect/MetricSelectScene.tsx
- src/MetricSelect/api.ts
- src/README.md
- src/helpers/MetricDatasourceHelper.ts
- src/otel/api.test.ts
- src/otel/api.ts
- src/otel/util.ts
Deprecate "Explore Metrics" in favor of "Metrics Drilldown"
Fixes https://github.com/grafana/metrics-drilldown/issues/96
> Chore: Update copy and comments to refer to Metrics Drilldown

- .github/workflows/bundle-stats-create.yml
This PR is an attempt to avoid failures in [`bundle-stats-compare.yml` runs](https://github.com/grafana/metrics-drilldown/actions/workflows/bundle-stats-compare.yml runs) that seem to arise because the `main-branch-stats` artifact can't be found.
> ci: persist bundle stats for 90 days

- src/RelatedLogs/RelatedLogsScene.tsx
Similar pattern used in logs drilldown.
https://github.com/grafana/logs-drilldown/blob/main/src/services/query.ts#L57
> feat(logs): add `supportingQueryType` to identify requests done from plugin

- .github/workflows/plugins-catalog.yml
This PR supports #20.
This is a temporary workaround until we can merge #122. It allows us to publish the app to the Grafana plugins catalog. This new workflow is heavily inspired by https://github.com/grafana/explore-profiles/blob/main/.github/workflows/update-plugins-catalog.yml.
> ci: update plugins catalog

- .github/workflows/plugins-catalog.yml
#20 
Taking inspiration from https://github.com/grafana/irm/blob/073065d0237dbc639ffbae1fa34fbc41a51f575f/.github/actions/build-and-publish-plugin-artifact/action.yml, let's see if this update vault path helps the [plugin catalog workflow](https://github.com/grafana/metrics-drilldown/actions/workflows/plugins-catalog.yml) pass.
> ci: change vault path

- .github/workflows/plugins-catalog.yml
This PR supports #20.
Yet another attempt to get this workflow running. More closely following https://github.com/grafana/oncall/blob/3bd20edb661d4ea047bd937ed75638f097d4a651/.github/workflows/on-release-published.yml this time.
> ci: unset vault instance

- .github/workflows/plugins-catalog.yml
This PR supports #20.
Fixes a mistake in `.github/workflows/plugins-catalog.yml`, and more closely follows the patterns from:
- https://github.com/grafana/explore-profiles/blob/main/.github/workflows/update-plugins-catalog.yml
- https://github.com/grafana/oncall/blob/main/.github/workflows/on-release-published.yml
> ci: update vault access pattern

- src/WingmanDataTrail/HeaderControls/HeaderControls.tsx
- src/WingmanDataTrail/MetricsReducer.tsx
- src/WingmanDataTrail/SideBar/MetricsFilterSection.tsx
- src/WingmanDataTrail/SideBar/SideBar.tsx
**before changes**
https://github.com/user-attachments/assets/fe3ca485-a0ec-4014-afaa-a835234f340a
**after changes**
https://github.com/user-attachments/assets/a05ae7f6-14bd-4225-a5a2-b18ed25960bc
**bug**: when scrolling the Data source header and teh Search metrics header have different sticky-ness so it looks weird
https://github.com/user-attachments/assets/753e855f-b9cd-4cff-89f3-931da80c42e8
> Style: Make sidebar and header fixed

- README.md
- src/README.md
- src/plugin.json
- Updates the repo-level README and the README published to the plugins catalog, to improve clarity, accuracy, and naming correctness.
- Updates the `plugin.json` config for naming correctness and rearranges keywords for plugin catalog search.
Please check out:
- the README that'll be visible in the Grafana plugins catalog: https://github.com/grafana/metrics-drilldown/blob/chore/prepare-app-for-prod-plugins-catalog/src/README.md
- the repo-level README: https://github.com/grafana/metrics-drilldown/tree/chore/prepare-app-for-prod-plugins-catalog?tab=readme-ov-file#grafana-metrics-drilldown
> docs: prepare app for prod plugins catalog

- src/plugin.json
- src/stubs/moment-timezone.ts
- webpack.config.ts
This PR does a couple of things:
We're now stubbing another transitive dependency (from `@grafana/prometheus`) that was adding unnecessary heft to our bundle. Check out the results of `npm run analyze` before and after this change:
This PR adds [`preload` config](https://grafana.com/developers/plugin-tools/reference/plugin-json) to load the app before users navigate to it. This is something that other Drilldown apps do, and we should feel free to also, since we've taken steps to keep the bundle size under control and use code splitting (in https://github.com/grafana/metrics-drilldown/pull/56, https://github.com/grafana/metrics-drilldown/pull/64, and this PR).
Note that `preload` is not the same as "preinstall." Preinstall is taken care of by https://github.com/grafana/grafana/pull/100094. …
> perf: preload app and reduce bundle size

- package-lock.json
- package.json
- src/WingmanDataTrail/MetricVizPanel/MetricVizPanel.tsx
- src/WingmanDataTrail/MetricVizPanel/actions/ApplyAction.tsx
- src/WingmanDataTrail/MetricVizPanel/actions/ConfigureAction.tsx
- src/WingmanDataTrail/MetricVizPanel/buildPrometheusQuery.ts
- src/WingmanDataTrail/MetricVizPanel/panels/statushistory.tsx
- src/WingmanDataTrail/MetricVizPanel/panels/timeseries.tsx
- src/WingmanDataTrail/MetricsReducer.tsx
This PR adds opinionated visualization for uptime/downtime metrics. By using the [Status History](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/status-history) panel, we can enjoy clearer visual feedback about uptime/downtime. For uptime metric, we also use the `min()` function to highlight downtime in any of the metric's series.
This PR also experiments with using [`@grafana/promql-builder`](https://github.com/grafana/promql-builder) instead of string interpolation for PromQL query expression building.
> Hackathon: Opinionated handling of uptime/downtime

- docker-compose.yaml
- src/App/App.tsx
- src/Integrations/logs/base.ts
- src/Integrations/logs/labelsCrossReference.ts
- src/Integrations/logs/lokiRecordingRules.ts
- src/MetricGraphScene.tsx
- src/MetricScene.tsx
- src/RelatedLogs/NoRelatedLogsFoundScene.tsx
- src/RelatedLogs/RelatedLogsManager.ts
- src/RelatedLogs/RelatedLogsOrchestrator.ts
- src/RelatedLogs/RelatedLogsScene.tsx
- src/interactions.ts
- src/shared.ts
This PR closes #119.
This PR extracts logic from the Related Logs scene to display a count of related logs in the Metric scene's action view tabs. Most of the orchestration of related logs is now handled in a new utility class (`src/RelatedLogs/RelatedLogsOrchestrator.ts`).
Other changes include:
- When the related logs feature is enabled, we now track the number of related logs that exist when a user clicks on an Action View tab. The related logs count is only reported when conditions have been met to show related logs (e.g. when at least one label filter has been applied, or the selected metric is the product of a Loki recording rule). 
- The `NoRelatedLogsScene` has a new look and updated messaging, which aims to improve clarity.
- The logs DS picker now filters out data sources with …
> RelatedLogs: Display count of found logs in the Related Logs tab

- package-lock.json
- package.json
This PR bumps to the next prerelease version, `1.0.0-2`. This will keep the `version` in line with the forthcoming `1.0.0-2` tag.
> chore: bump prerelease version

- .github/workflows/bundle-stats-create.yml
A troublesome conditional is preventing the `build-stats` job from uploading bundle size artifacts when `.github/workflows/bundle-stats-create.yml` is run via workflow dispatch.
> ci: fix workflow dispatch

- src/Menu/PanelMenu.tsx
Fixes https://github.com/grafana/metrics-drilldown/issues/170
The open in explore link that is in the panel (not the open in explore icon) was not interpolating the metric in the expression passed to the explore query editor. This fixes that.
How to Test:
1. Select a metric in GMD.
2. See the metric panel.
3. Find the hamburger dots in the large metric panel.
4. Click explore link from the dots.
5. See that the query open in explore query editor has the metric correctly interpolated.
> Bug fix: Fix explore link in panel using metricScene

- CHANGELOG.md
- package-lock.json
- package.json
Runs `npm version prerelease` to:
- Update the project's version to `1.0.0-4` in `package.json` & `package-lock.json`
- Adds the release notes for the forthcoming `v1.0.0-4` tag to the changelog
> chore: prerelease 1.0.0 4

- src/README.md
- src/plugin.json
Make our CI workflow only test against 11.6.0-82198 and newer
> Chore: Set Grafana version 11.6.0-82198 as oldest supported version

- src/MetricSelect/AddToExplorationsButton.tsx
- src/utils.ts
Corresponding PR for https://github.com/grafana/investigations-app/pull/229 to pass fieldConfig to the investigations app in order to keep same colors, etc of panels.
> feat(investigations): add `fieldConfig` to investigations context

- src/WingmanDataTrail/MetricVizPanel/MetricVizPanel.tsx
- src/autoQuery/units.ts
fixes https://github.com/grafana/metrics-drilldown/issues/192
the y-axis of the panels now displays units like 's' for seconds-based metrics such as CPU metrics, 'bytes' for byte-based metrics, etc. Grafana automatically formats these units appropriately (e.g., converting bytes to KB, MB, GB as needed).
changes in `units.ts`
https://github.com/user-attachments/assets/9f9acb01-6802-470f-8e60-a9c5fc7bc3b7
https://github.com/user-attachments/assets/6ab62a09-bec0-4277-80af-2c31d1b32c17
> fix: display unit in metric panel y-axis

- README.md
- docker-compose.yaml
A few of things:
1. Upgrade to Grafana 11.6 (released yesterday) and enable the `exploreMetricsUseExternalAppPlugin` feature toggle. This allows Grafana Metrics Drilldown app to move from **More apps** to **Drilldown** > **Metrics** where it belongs.
2. Removes the `container_name` for our Prometheus container. This avoids container name collisions with other services you might be running locally.
3. Updates the local dev docs to more pointedly describe how to see the local app.
After checking out the `chore/upgrade-grafana` branch and running `npm run server` to rebuild our containers, observe that **More apps** no longer contains our app, and **Drilldown** > **Metrics** routes to `/a/grafana-metricsdrilldown-app`, like so:
> chore: upgrade grafana to 11.6

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- src/version.ts
This PR intends to overcome some flakiness with the current `grafana-dev@12` image.
For a couple of workflows (that build GCS artifacts and publish to the Grafana plugins catalog), add a Workflow Dispatch [option](https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows) to skip running e2e tests with the dev image.
We'll need to merge this to test.
> ci: add option to skip dev image

- src/plugin.json
This PR aims to make one of the three UX experiments from #131 the default experience. This version of the app will be used in a staging environment for the purposes of collecting feedback.
The plugin config has been updated to make the `/onboard-filters-sidebar` route the default experience when clicking **Drilldown** > **Metrics**.
As an escape hatch, we offer users the ability to go to the **Home** page, where they can get to the original `/trails` experience if desired.
https://github.com/user-attachments/assets/5b331490-b564-47c3-864f-ee56ef3e90e2
> feat: default to onboard filters sidebar

- package-lock.json
- package.json
- src/App/App.tsx
- src/constants.ts
- src/tracking/__tests__/getEnvironment.spec.ts
- src/tracking/faro/__tests__/faro.spec.ts
- src/tracking/faro/faro-environments.ts
- src/tracking/faro/faro.ts
- src/tracking/faro/getFaroEnvironment.ts
- src/tracking/getEnvironment.ts
**Related issue(s):** resolves https://github.com/grafana/metrics-drilldown/issues/226
This PR adds [Faro instrumentation](https://grafana.com/docs/grafana-cloud/monitor-applications/frontend-observability/).
4 different frontend applications have been created in ops:
- **local:** for local tests
- **dev:** for capturing data from `grafana-dev.net`
- **ops:** for capturing data from `grafana-ops.net`
- **prod:** for capturing data from `grafana.net`
When the app is started, Faro is initialized with useful metadata (app name, release, git commit, environment, user email). 
During a user session, the browser's URL host is used to determine to which collector the tracking data should be sent. 
Some unit tests have been provided to prevent changes in the collector's URLs .
- Locally by …
> feat: Instrument the plugin with Faro

- src/App/App.tsx
- src/App/ErrorView.tsx
- src/App/InlineBanner.tsx
- src/tracking/logger/logger.ts
**Related issue(s):** resolves https://github.com/grafana/metrics-drilldown/issues/195
This PR adds an error boundary to the app:
- to capture any runtime exception or unhandled promise rejection,
- to present a human-friendly message to the user
This PR also introduces a `Logger` class for consistent logging and error reporting.
The changes are pretty straightforward, see the diff tab.
- Manually, by enabling [Faro in local](https://github.com/grafana/metrics-drilldown/blob/staging/src/tracking/faro/faro-environments.ts#L5-L13) and adding a statement in the code to throw an error: an error inline banner should be displayed and the error should appear in our FE O11Y app in ops
> feat(*): Add error boundary + logger

- e2e/fixtures/css/hide-app-controls.css
- e2e/fixtures/views/MetricsReducerView.ts
- e2e/fixtures/views/SelectMetricView.ts
- src/DataTrail.tsx
- src/WingmanDataTrail/GroupBy/MetricsGroupByList.tsx
- src/WingmanDataTrail/MetricsList/SimpleMetricsList.tsx
- src/WingmanDataTrail/MetricsReducer.tsx
- src/WingmanDataTrail/SideBar/LabelsBrowser.tsx
- src/WingmanOnboarding/HeaderControls/MainLabelVariable.tsx
- src/WingmanOnboarding/MetricsOnboarding.tsx
- tests/metrics-reducer-view.spec.ts
- tests/onboarding-view.spec.ts
**Related issue(s):** relates to https://github.com/grafana/metrics-drilldown/issues/188
This PR adds 2 missing variant tests for the metrics reducer and new tests for the onboarding flow
Generally speaking, we duplicate quite some code, knowing that we'll DRY as soon as we have a winning variant.
See diff tab for specific comments.
> test(E2E): Add more WingMan tests

- src/App/App.tsx
- src/App/InlineBanner.tsx
- src/App/useCatchExceptions.ts
- src/WingmanDataTrail/GroupBy/MetricsGroupByList.tsx
- src/WingmanDataTrail/GroupBy/MetricsGroupByRow.tsx
- src/WingmanDataTrail/MetricsList/SimpleMetricsList.tsx
- src/WingmanOnboarding/GroupBy/MetricsGroupByRow.tsx
- src/WingmanOnboarding/MetricsOnboarding.tsx
**Related issue(s):** follow-up of https://github.com/grafana/metrics-drilldown/pull/228
This PR adds some tweaks to ensure that all runtime errors are consistently reported. Unfortunately, we have to bypass specific errors to ensure banners don't appear where they shouldn't. See the comments in  see `src/App/useCatchExceptions.ts`.
In a future PR, we should refactor WingMan to better live alongside DataTrail, namely:
- moving the variables from the `DataTrail` Scene object to the WingMan's Scene objects were they are used
- handle better the request cancellations in DataTrail
I've created a GitHub issue to work on this ASAP: https://github.com/grafana/metrics-drilldown/issues/231
See diff tab
- Same as described in the linked PR above, all uncaught runtime exceptions _and_ unhandled …
> feat(Faro): Better error reporting

- src/App/App.tsx
**Related issue(s):** follow-up of https://github.com/grafana/metrics-drilldown/pull/230
This PR removes the `ErrorBoundary` component (but keeps the global error handlers) as an attempt to prevent the errors that occur when trying to async load the JS chunks. E.g.:
It's a shot in the dark as the root cause of the error has not yet been identified.
See diff tab
- The uncaught exceptions / unhandled promise rejections should still be reported and, hopefully, there shouldn't be any "loading chunk" errors.
> fix(App): Remove the ErrorBoundary component

- src/DataTrail.tsx
Bug fix
**Related issue(s):** 
Fixes https://github.com/grafana/support-escalations/issues/14997
Fixes https://github.com/grafana/metrics-drilldown/issues/234
Fixes https://github.com/grafana/grafana/issues/101556
This PR removes `__name__` from the Prometheus label filters that are interpolated in the query. 
This only changes the filters in the query and does not change the behavior of the `MetricSelectScene` that uses filters that may include __name__ to reduce the list of metric names.
We will have to keep an eye on the Metrics Reducer and how it uses the filters. If it gets the expression, we will have to explicitly use the filters.filters to get access to `__name__` to use that to reduce the list of metrics names.
1. Open the Metrics Drilldown app.
2. Select the legacy drilldown …
> Bug fix: Remove __name__ from query filters expression

- src/DataTrail.tsx
- src/MetricSelect/MetricSelectScene.tsx
See this issue for full context 🙏🏻  https://github.com/grafana/metrics-drilldown/pull/235
This PR fixes a regression from the above bug fix. The regression was that `variableDependency` in MetricSelectScene only listened for changes in the `expr`. Since we filtered `__name__` from that, the metrics list was not being refreshed correctly. 
The fix for this is to listen to state changes on the VAR_FILTERS variable instead. This will show when the __name__ label is updated, event though it is no longer interpolated in the expression.
Open the Metrics Drilldown app.
Select the legacy drilldown experience.
Select a filter __name__ and choose a metric name.
See that the list of metrics filters for that metric.
See that the query does not break with the error "metric name set twice."
Confirm …
> Bug fix: __name__ bug continued

- .github/workflows/playwright-published.yml
**Related issue(s):** follow-up of https://github.com/grafana/metrics-drilldown/pull/171
This PR ensures we launch Playwright in a Docker container after merging a PR to main
See diff tab
- After merging this PR, the build in main should pass
> ci(Playwright): Add missing params when launching Playwright against main

- src/App/ErrorView.tsx
Whenever a runtime error occurs, we display a banner suggesting to the user to reload the page. But if the error comes from some incorrect values of the URL search parameters, reloading does not have any effect. 
This PR is an attempt to fix this situation by providing a link to reload the page properly:
| <img width="887" alt="image" src="https://github.com/user-attachments/assets/ea6d9417-a40a-4c05-abe8-9a3e8593542f" /> | <img width="874" alt="image" src="https://github.com/user-attachments/assets/c3f5ed5b-0ad3-403d-9819-79c3517c041e" />  |
In a future PR, we'll handle the specific case where a data source is set in the URL search parameters, but does not exist.
The link generated keeps only the timerange parameters `from`, …
> feat(ErrorView): Provide a link for a clean page reload

- .github/workflows/publish.yml
This prevents undesired runs of `publish.yml` from a non-`main` branch, when pushing tags along with a commit.
In our publish workflow:
- Update the instructions for creating a new version, for accuracy & reproducibility
- In response to a `push`, the workflow runs only when the branch is `main` and the ref contains a `v*` tag
This is a case of "merge it, then we'll see."
> ci: prevent publishing from non-default branch

- CHANGELOG.md
- package-lock.json
- package.json
This PR handles the up-versioning to the next prerelease version, by following the steps outlined here (note: versioning only, without association to a particular feature branch):
https://github.com/grafana/metrics-drilldown/blob/f39e3fe138276569af8701042e43dc24d48d7bb3/.github/workflows/publish.yml#L4-L15
- Updated the changelog with a link to the forthcoming release notes for this version
- Ran `npm version prerelease`, then `git push origin version/1.0.0-6 --follow-tags`
N/A
> chore: versioning for prerelease 1.0.0-6

- src/helpers/MetricDatasourceHelper.ts
When navigating from Grafana side menu => metrics drilldown => let's start there is a race condition when loading metadata in the `MetricDatasourceHelper`. Sometimes metadata is already loaded due to DataTrail being initialized at least 2 times (which is still a mystery). This fixes the logic so that metadata can be loaded earlier, then stored on the `MetricDatasourceHelper`, then accessed correctly for native histogram checks.
Check for metadata loaded on the ds separately from loaded in the `MetricDatasourceHelper`.
1. Open Grafana
2. Click the side menu
3. Click metric drilldown
4. Click Let's start
5. gdev-prometheus data source should be loaded (it has native histograms)
6. See the banner for native histograms
> Bug: fix race condition bug with loading metadata for native histograms

- src/Breakdown/LabelBreakdownScene.tsx
This PR prevents [this runtime error](https://ops.grafana-ops.net/a/grafana-kowalski-app/apps/48/errors?from=now-24h&to=now&timezone=utc&frameIndex=0&var-error_text=e.fields%5B1%5D%20is%20undefined&var-error_hash=7388802338371670933&var-show_errors_drawer=1&var-error_session_id=Lqpv0aw9qH) to occur.
See diff tab
`-`
> fix(LabelBreakdownScene): prevent runtime error

- .github/workflows/publish.yml
This fixes `publish.yml` failures like https://github.com/grafana/metrics-drilldown/actions/runs/14321602690/job/40139564146 which were preventing publishing to the Grafana Plugins Catalog.
In our `publish.yml` workflow, Docker-related workflow config wasn't set for `grafana/plugin-ci-workflows/.github/workflows/cd.yml@main`'s call of `grafana/plugin-ci-workflows/.github/workflows/ci.yml@main`.
Now that https://github.com/grafana/plugin-ci-workflows/pull/70 has been merged, we can pass the requisite config.
N/A
> cd: provide necessary docker inputs

- src/WingmanDataTrail/GroupBy/MetricsWithLabelValue/MetricsWithLabelValueVariable.ts
- src/WingmanDataTrail/MetricsReducer.tsx
- src/WingmanDataTrail/MetricsVariables/EventMetricsVariableLoaded.ts
- src/WingmanDataTrail/MetricsVariables/EventMetricsVariableUpdated.ts
- src/WingmanDataTrail/MetricsVariables/FilteredMetricsVariable.ts
- src/WingmanDataTrail/MetricsVariables/MetricsVariableFilterEngine.ts
- src/WingmanDataTrail/MetricsVariables/MetricsVariableSortEngine.ts
- src/WingmanDataTrail/MetricsVariables/withLifecycleEvents.ts
**Related issue(s):** follow-up of https://github.com/grafana/metrics-drilldown/pull/271
This PR is the 2nd part of the refactor we discussed in our ensemble session. 
See diff tab for specific comments.
Same as in https://github.com/grafana/metrics-drilldown/pull/271, but taking also in consideration sorting options
We'll add E2E tests in a future PR.
> refactor(Variables): Decouple metric variables from the UI component used for sorting

- src/WingmanDataTrail/GroupBy/MetricsGroupByRow.tsx
**Related issue(s):** solves https://github.com/grafana/metrics-drilldown/issues/252
We still need to figure exactly how the UX should work for the "Include/Exclude" buttons.
So, in the meantime, this PR changes them for a single "Select" button which, once clicked, updates the AdHoc filters on top of the page and resets the "Group by" option to `(none)`:
| <img width="1703" alt="image" src="https://github.com/user-attachments/assets/43fc084d-47f4-43e1-92ec-1e7c5e2e4e8f" /> | <img width="1703" alt="image" src="https://github.com/user-attachments/assets/e685a108-b46a-4c51-a7af-eafb587b55ed" /> |
See diff tab
`-`
> feat(GroupBy): Change "Include/Exclude" buttons for a single "Select" button

- .github/workflows/bundle-stats-create.yml
Although we specify `retention-days: 90` for `main-branch-stats` in `.github/workflows/bundle-stats-create.yml`, the bundle size stats inexplicably cannot be found if the `main` branch hasn't been updated recently. This PR doesn't address the unknown root cause of that issue, but it provides a workaround: generate the bundle size stats once per day. This should help prevent erroneous [failures](https://github.com/grafana/metrics-drilldown/actions/workflows/bundle-stats-compare.yml?query=is%3Afailure) of the Bundle Stats workflow.
> ci: generate main branch bundle stats daily

- src/extensions/links.ts
- src/plugin.json
**Related issue(s):**  This PR #298.
The goal of this PR is to add a missing [link](https://grafana.com/developers/plugin-tools/how-to-guides/ui-extensions/create-an-extension-point) from Explore to Grafana Metrics Drilldown when a user crafts a PromQL expression in the Prometheus data source.
This PR builds on #275 and adapts the `PluginExtensionPoints.DashboardPanelMenu` link's [`configure`](https://grafana.com/developers/plugin-tools/reference/ui-extensions#addlink) function to work for the `PluginExtensionPoints.ExploreToolbarAction` extension point also.
> [!NOTE]  
> Testing this requires running `grafana/grafana`.
Simply check out the `298/add-missing-link-to-toolbar-action` branch, then `npm run dev`.
1. Start by pulling `grafana/grafana`'s latest `main`.
2. Make your local …
> fix: add missing link to "Go queryless" toolbar action

- src/WingmanDataTrail/SideBar/SideBar.tsx
- src/interactions.ts
create rudderstack event for sidebar toggle
Ref https://github.com/grafana/metrics-drilldown/issues/304
1. Added a new event type `metrics_sidebar_toggled ` to the `Interactions` interface in `src/interactions.ts` with these properties:
- `action`: Either 'opened' or 'closed'
- `section`: Optional string indicating which section was opened/closed
2. Updated the `SideBar` component to report the event in two places:
- In the `setActiveSection` method when a section is opened or closed
- In the close button's onClick handler to capture when the X button is clicked
I added `console.log`s in the code locally and saw them appear when toggling the sidebar in the UI
https://github.com/user-attachments/assets/55188403-7211-4500-b7d0-88e121c21c13
> chore: create rudderstack event for sidebar toggle

- src/MetricSelect/MetricSelectScene.tsx
Deprecate OTel, add new tooltip info with links and update the badge color
OTel is being deprecated. [See slack thread for more context](https://raintank-corp.slack.com/archives/C0630AYC4SY/p1745251701160449)
1. [The label promotion initiative is complete and we are promoting resource attributes labels](https://grafana.com/docs/mimir/latest/configure/configure-otel-collector/#work-with-default-opentelemetry-labels)
a. [more discussion here with promoting resource attributes in Mimir](https://raintank-corp.slack.com/archives/C080PBH5RDX/p1745248945524559?thread_ts=1741679535.372499&cid=C080PBH5RDX)
2. Deprecating the join query supports the [Grafana Drilldown Principal 2](https://docs.google.com/document/d/14WWJ1yF2oN1GLLxD_nCeksa9MOWtaajZeQK0pLoZYtI/edit?tab=t.0#heading=h.cfa5lf38g7md), …
> deprecate OTel message

- e2e/fixtures/views/SelectMetricView.ts
This is a one-liner that's required to get e2e tests working after https://github.com/grafana/metrics-drilldown/pull/312 was merged.
> fix: e2e test selector

- src/DataTrail.tsx
- src/WingmanDataTrail/SideBar/SideBar.tsx
- src/shared.ts
This PR is a POC of an idea that we'd like to test and get feedback on.
When using metric filters from the MetricsReducer sidebar (metric name prefix, suffix, or rule type), you must interact with the sidebar (either by hovering over selected filter icons, or opening the sidebar) to see the current filter selections. It'd be nice to have at-a-glance feedback about the filters that have been applied, without any sidebar interaction. Or so we think! Let's get feedback on this :)
- Adds a new read-only `VAR_OTHER_METRIC_FILTERS` variable
- `VAR_OTHER_METRIC_FILTERS`'s filters are kept in sync with the currently-applied prefix, suffix, and rule group filters
- When no prefix, suffix, or rule group filters are applied, the `VAR_OTHER_METRIC_FILTERS` variable is hidden
1. Check out the …
> poc: other metric filters

- src/pages/TrailWingman.tsx
Fixes a bug where having a metric selected and then refreshing would take you to the reducer instead of the proper view
> fix: removing empty state start

- src/WingmanDataTrail/MetricsVariables/computeRulesGroups.ts
- src/WingmanDataTrail/SideBar/sections/MetricsFilterSection/CheckBoxList.tsx
- src/WingmanDataTrail/SideBar/sections/MetricsFilterSection/MetricsFilterSection.tsx
**Related issue(s):** This PR supports https://github.com/grafana/metrics-drilldown/pull/310 (and by extension, https://github.com/grafana/metrics-drilldown/issues/304).
This refactor aims to reduce the likelihood of disagreements between the rule group labels defined in `src/WingmanDataTrail/MetricsVariables/computeRulesGroups.ts` and the rule group handling logic (see the `switch` statement) in `src/WingmanDataTrail/SideBar/sections/MetricsFilterSection/MetricsFilterSection.tsx`.
> refactor: rule group labels

- package.json
This PR fixes a script that was updated in https://github.com/grafana/metrics-drilldown/pull/318.
> test: fix watch script

- e2e/tests/metrics-reducer-view.spec.ts
- src/WingmanDataTrail/Labels/LabelsDataSource.ts
This PR aims to fix recent `grafana-dev@12.x` e2e test failures.
1. Adjusts the handling of `@grafana/prometheus`' `languageProvider.fetchLabelsWithMatch` function, which acquired another new parameter in https://github.com/grafana/grafana/pull/101705. The way this PR handles the conditional statement should accommodate any further addition of parameters to this function.
2. Adds a new assertion to `e2e/tests/metrics-reducer-view.spec.ts` to reduce flakiness.
All CI should pass.
> fix: grafana 12 dev e2e

- src/WingmanDataTrail/ListControls/ListControls.tsx
**Related issue(s):** fixes https://github.com/grafana/metrics-drilldown/issues/332
| <img width="1699" alt="image" src="https://github.com/user-attachments/assets/0d9ebaa7-7270-4ae5-a391-c3eb7f68fbad" /> | <img width="1701" alt="image" src="https://github.com/user-attachments/assets/2773de5b-7935-4f27-86a9-3c37d15c5d3c" /> |
`-`
> fix(ListControls): Fix extra padding between sort and layout switch

- src/DataTrailsHome.tsx
- src/banners/HomepageDeprecationBanner.tsx
Supports: https://github.com/grafana/metrics-drilldown/issues/255
Uses localStorage to only show it once
> chore: homepage deprecation warning

- src/WingmanDataTrail/GroupBy/MetricsWithLabelValue/MetricsWithLabelValueDataSource.ts
- src/WingmanDataTrail/GroupBy/MetricsWithLabelValue/MetricsWithLabelValueVariable.ts
**Related issue(s):** `.`
Before this PR, the ad hoc filters were not applied when a "group by" label had been selected.
|<img width="1703" alt="image" src="https://github.com/user-attachments/assets/77fb5f26-c9e2-4aed-9954-1d414cf4ed65" />  | <img width="1703" alt="image" src="https://github.com/user-attachments/assets/2c469b12-5e93-43b9-8109-669aecda3c71" /> |
See diff tab
- Open the side bar to select a "group by" label
- Add some filters in the app header
- The metrics for each label should correspond to the selected filters
> fix(MetricsReducer): Apply ad hoc filters when group by is active

- src/Breakdown/AddToFiltersGraphAction.tsx
- src/Breakdown/LabelBreakdownScene.tsx
- src/MetricSelect/SelectMetricAction.tsx
- src/WingmanDataTrail/MetricVizPanel/actions/ApplyAction.tsx
- src/WingmanDataTrail/MetricVizPanel/actions/SelectAction.tsx
**Related issue(s):** solves https://github.com/grafana/metrics-drilldown/issues/345
See [this Slack thread](https://raintank-corp.slack.com/archives/C075BDBTX96/p1745508389865759) for the rationale and consensus.
**Metrics reducer:**
**Configure drawer:**
**Breakdown (uses a secondary variant):**
**Related metrics:**
`-`
> feat(PanelActions): Use outline style buttons throughout the app

- src/Breakdown/ByFrameRepeater.tsx
- src/Breakdown/LabelBreakdownScene.tsx
- src/Breakdown/SortByScene.tsx
- src/WingmanDataTrail/MetricsReducer.tsx
- src/interactions.ts
- src/services/store.ts
**Related issue(s):** This PR supports #304.
The goal of this PR is to extend event tracking for `sortBy`, to capture sorting changes in the Metrics Reducer. Previously, we were tracking `sortBy` in the context of the breakdown scene, when selecting a label name (not "All"):
This PR adapts the `'sorting_changed'` interaction to deal with sorting changes in both the label breakdown scene and the metrics reducer. By using a [discriminated union](https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes-func.html#discriminated-unions) in `src/interactions.ts`, we can support both Sort By controls (each with their own options) with great type safety (`sortBy` values match the options in each scene).
> chore: track sort by usage in the metrics reducer

- src/WingmanDataTrail/ListControls/QuickSearch/QuickSearch.tsx
- src/WingmanDataTrail/MetricsReducer.tsx
- src/interactions.ts
create rudderstack event for quick search
event only fires after a user has stopped typing for 1 second to prevent firing the event multiple times for a single search
ref https://github.com/grafana/metrics-drilldown/issues/304
1. added new event type `quick_search_used` to `Interactions` interface
2. report the event when user types into quick search bar 
i added `console.logs` in the code locally and saw them appear when typing into the quick search bar. you can see that typing quickly (alert) and slowly (kube) fires the event one time each
https://github.com/user-attachments/assets/e753e42c-3eaa-4dc9-874f-8964e00a7282
> chore: create rudderstack event for quick search

- src/helpers/MetricDatasourceHelper.ts
**UPDATE** ❇️❇️❇️❇️❇️❇️❇️❇️❇️❇️❇️❇️❇️❇️
The most up to date signature is 3 parameters
[A limit param was added recently](https://github.com/grafana/grafana/pull/101705/files#r2074252669).
Old versions still require a check > 1. As long as we check for > 1 we still cover the issue of Timerange being the first parameter.
❇️❇️❇️❇️❇️❇️❇️❇️❇️❇️❇️❇️❇️❇️❇️❇️❇️❇️
**What is this?** Bug fix with changed signature
**What code was changed**
`fetchLabelValues` old signature had one parameter.
The new signature has two.
So, we should check for >1 when we need to add the timerange parameter.
**How to test?**
Group by labels should not break like this
> Bug: fetchLabelValues old params were 1 and new with Timerange are 2

- CHANGELOG.md
- package-lock.json
- package.json
This PR bumps the version to `1.0.0` and updates the changelog accordingly.
> chore: bump version to 1.0.1

- src/README.md
**Related issue(s):** https://github.com/grafana/metrics-drilldown/issues/286
This PR updates a doc link in the readme to point to the new docs.
> docs: Update doc link in readme

- e2e/tests/metrics-reducer-view.spec.ts
A change [here](https://github.com/grafana/metrics-drilldown/pull/376/files#diff-889ff398a9844294fd45acd689975a41466b984ef8b124b1cae2013f159126f7) caused an e2e test to be flaky.
This PR restores the `expect(...).toPass()` wrapper around the usage count assertion. This tells Playwright to keep trying the assertion until is passes, which avoids erroneous failures caused by loading behavior. For context on the `expect(...).toPass()` pattern, see https://playwright.dev/docs/test-assertions#expecttopass.
All CI should pass.
> fix: retry until assertion passes

- jest.config.js
- src/Breakdown/LabelBreakdownScene.tsx
- src/MetricScene.tsx
- src/WingmanDataTrail/MetricsReducer.tsx
- src/WingmanDataTrail/SideBar/SideBar.tsx
- src/WingmanDataTrail/SideBar/sections/BookmarksList.tsx
- src/WingmanDataTrail/SideBar/sections/LabelsBrowser/LabelsBrowser.tsx
- src/WingmanDataTrail/SideBar/sections/MetricsFilterSection/MetricsFilterSection.tsx
- src/interactions.ts
- src/mocks/interactionsMock.ts
This PR adds some metadata to the tracking events: the app version number and GIT commit, so we can understand better the tracking event we receive.
Additionally, wherever it's needed, it moves the calls to `reportExploreMetrics` to the top of the function body they're part of. We do this to ensure we always capture the user intent, even if the rest of the function body creates a runtime exception.
See diff tab
> chore: Tracking updates

- src/MetricsDrilldownDataSourceVariable.ts
- src/utils/utils.datasource.test.ts
- src/utils/utils.datasource.ts
**Related issue(s):** 
This is follow up work from this comment here https://github.com/grafana/grafana/pull/103482#pullrequestreview-2753315294.
This adds support for cloud partners Prometheus data sources. https://github.com/grafana/grafana-amazonprometheus-datasource and https://github.com/grafana/azure-prometheus-datasource.
Updated the `isPrometheusDataSource` in `src/utils/utils.datasource.ts` to check if a data source is a core Prom, or cloud partner Prom data source.
Updated `src/MetricsDrilldownDataSourceVariable.ts` to use `isPrometheusDataSource` so that the following scenario will work correctly:
- Configure a core prometheus data source
- Configure an Amazon or Azure prometheus data source
- Go to the metrics drilldown page and in the data source variable dropdown select the …
> feat: add support for cloud partners Prometheus data sources

- src/services/sorting.test.ts
- src/services/sorting.ts
**Related issue(s):** This PR fixes https://github.com/grafana/metrics-drilldown/issues/455.
The goal is to fix an error related to an unhandled case (empty series) when sorting label values in the Metric scene's Breakdown tab.
1. I wrote an "empty series" test that failed before the fix.
2. A sorting function was updated to handle empty series.
> Breakdown: Fix sorting with empty series fields

- .github/workflows/ci.yml
- .github/workflows/playwright-published.yml
- .github/workflows/publish.yml
Pin actions to current `main` commit
I have this PR: https://github.com/grafana/plugin-ci-workflows/pull/103
That will enable us to further minimize our docker config on this other PR:
https://github.com/grafana/metrics-drilldown/pull/451
But if i merge right now it could break our `Playwright Published` workflow. This prevents that from happening and allow us to update with confidence.
> chore: pinning plugin-ci-workflows actions

- docker-compose.yaml
- e2e/provisioning/prometheus/prometheus.yml
Seems like other containers use `prometheus` name for the service so lets be a bit more specific on our use case
```sh
npm run dev
npm run server
npm run e2e:ci
```
> re-name prometheus to prometheus-gmd

- src/App/App.tsx
- src/App/Onboarding.tsx
- src/App/Routes.tsx
- src/App/useListPrometheusDataSources.ts
- src/App/useTrail.tsx
**Related issue(s):** resolves https://github.com/grafana/metrics-drilldown/issues/473
This PR adds a simple onboarding screen when no Prometheus data source has been found on the instance:
In order to display the onboarding screen or not, this PR gets the list of data sources from Grafana runtime's configuration. See diff tab for specific comments.
- Checkout this branch in local
- Comment/remove all the YAML files in `./provisioning/datasources` to ensure no Prometheus data sources will be configured
- Delete any volume used by the `grafana-gmd` Docker container
- In a terminal, execute `npm run server`
- Go to http://localhost:3001/a/grafana-metricsdrilldown-app
- You should see the onboarding screen
> feat(App): Add onboarding screen when no Prometheus data sources

- e2e/docker/Dockerfile.playwright
- package-lock.json
- package.json
**Related issue(s):** [the build of the last commit to main has failed](https://github.com/grafana/metrics-drilldown/commit/1d2dbf4b4fcf36b239cf3231fd6c30af5d5f7efb)
The changes in this PR are the result of executing `./scripts/upgrade-playwright.sh 1.52.0 1.53.0` locally (see our [E2E testing docs](https://github.com/grafana/metrics-drilldown/blob/main/docs/end-to-end-testing.md#the-build-of-my-pr-has-failed-because-playwright-was-just-updated-how-to-fix-it)).
> chore(EndToEnd): Upgrade Playwright to v1.53.0

- src/Breakdown/MetricLabelsList/LabelVizPanel.tsx
- src/Breakdown/MetricLabelsList/behaviors/publishTimeseriesData.ts
- src/Breakdown/MetricLabelsList/transformations/addRefId.ts
- src/Breakdown/MetricLabelsList/transformations/sliceSeries.ts
This PR limits the number of series being rendered in the "Breakdown" tab to prevent the UI to be unresponsive:
This PR;
1. introduces a new `sliceSeries` data transformation in `LabelVizPanel`,
2. adds the cardinality in the panel title,
3. and adds a panel description when the number of series has been capped.
See diff tab for specific comments.
Manually, by checking with a "heavy" data source (one from ops, DM for details if needed)
> fix(MetricScene): Prevent high cardinality labels to make the UI unresponsive in the "Breakdown" tab

- e2e/docker/Dockerfile.playwright
- package-lock.json
- package.json
- src/helpers/MetricDatasourceHelper.ts
This PR upgrades Playwright to 1.53.1. We need this to fix CI failures like [this](https://github.com/grafana/metrics-drilldown/actions/runs/15741128673/job/44370769250?pr=504).
See diff tab.
All CI should pass.
> chore: upgrade playwright to 1.53.1

- src/WingmanDataTrail/MetricVizPanel/panels/buildTimeseriesPanel.ts
This PR intends to fix the CI issues that appeared in https://github.com/grafana/metrics-drilldown/pull/511.
Explicitly set the `pointSize` to `1` to avoid points from appearing unexpectedly.
1. On `main`, run `GRAFANA_IMAGE=grafana-dev GRAFANA_VERSION=12.1.0-249858 npm run e2e:server` and `npm run dev`
2. Look at `http://localhost:3001/a/grafana-metricsdrilldown-app/drilldown?nativeHistogramMetric=&layout=grid&filters-rule=&filters-prefix=go&filters-suffix=&from=2025-05-26T11:00:00.000Z&to=2025-05-26T12:05:00.000Z&timezone=utc&var-filters=&var-labelsWingman=%28none%29&search_txt=&var-metrics-reducer-sort-by=default&var-ds=gdev-prometheus&var-other_metric_filters=filters-prefix,prefix%7C%3D%7C` and notice that the time series panels have points during the static data time range used for …
> fix: use consistent line style in timeseries panels

- src/Breakdown/MetricLabelsList/behaviors/syncYAxis.ts
**Related issue(s):** follow-up of https://github.com/grafana/metrics-drilldown/pull/488
The logic to prevent updating the y axis of timeseries panel has a bug. This PR fixes it.
See diff tab
> fix(*): Fix y-axis sync logic

- e2e/config/playwright.config.common.ts
- e2e/tests/metrics-reducer-view.spec.ts
- src/autoQuery/buildPrometheusQuery.ts
- src/utils.ts
Addresses: https://github.com/grafana/support-escalations/issues/14997
> fix: Selecting __name__ as a filter breaks queries

- CHANGELOG.md
- package-lock.json
- package.json
This PR bumps the version to 1.0.5 from 1.0.4. We'll use the 1.0.5 tag as the basis for a new release.
Changelog and package.json + lockfile updated as per https://wiki.grafana-ops.net/w/index.php/Engineering/Grafana/Grafana_Explore/Metrics_Drilldown/Deployment_Handbook#Versioning.
N/A
> chore: bump version to 1.0.5

- .github/workflows/ci.yml
**Related issue(s):** see https://raintank-corp.slack.com/archives/C01C4K8DETW/p1751971692619869
See diff tab
- The `grafana-enterprise` E2E tests should be executed 
- The `grafana-dev` E2E tests should be skipped
> ci: Unblock build by skipping Grafana dev image in E2E tests

- src/App/useCatchExceptions.test.ts
- src/App/useCatchExceptions.ts
**Related issue(s):** Fixes #526
Before this PR, `errorEvent`s with falsey `error` properties (including errors originating from problematic browser extensions) were causing experience-breaking application errors.
This PR adjusts error handling, such that:
- Errors originating from browser extensions are logged and manually tracked with Faro (using `logger.error`) but don't make it to the error boundary.
- `errorEvent`s without an `error` property are logged and manually tracked with Faro (using `logger.error`) but don't make it to the error boundary. We are making an assumption that if an `errorEvent` doesn't have an `error` property, then it shouldn't be a Metrics Drilldown application error. We can revisit this assumption as needed.
All CI should pass, which implies that the tests …
> fix: exclude dubious errors from error boundary

- docker-compose.yaml
- src/RelatedLogs/OpenInLogsDrilldownButton.tsx
- src/RelatedLogs/RelatedLogsOrchestrator.ts
- src/RelatedLogs/RelatedLogsScene.tsx
- src/plugin.json
**Related issue(s):** This PR closes #524.
By leveraging the Grafana Logs Drilldown app's ability to generate links to certain Logs Drilldown views, we can improve the transition from Grafana Metrics Drilldown app's Related Logs scene to Grafana Logs Drilldown.
Before this PR, users could **Open Logs Drilldown** from the Related Logs tab, but this would only take them to the Logs Drilldown homepage, requiring them to re-apply label filters and time range settings before continuing their Drilldown journey.
- Adds a new [Extension Point](https://grafana.com/developers/plugin-tools/how-to-guides/ui-extensions/create-an-extension-point) to Metrics Drilldown to allow Logs Drilldown to create links to views with the correct label filters and time range (see companion PR, …
> feat: preserve labels and time range for logs drilldown

- src/helpers/MetricDatasourceHelper.ts
This PR adds an additional layer of safety in preparation for the eventual removal of deprecated `languageProvider` methods from the `@grafana/prometheus` package.
Although we shouldn't hit a case where the `dsUsesTimeRangeInLegacyLanguageProviderMethods` method is called for a version of `@grafana/prometheus` that doesn't have these functions (it should call the `queryLabelKeys`/`queryLabelValues` methods instead), this PR adds an additional check to the existence of the `languageProvider.fetchLabelValues` method before checking the number of parameters it has.
All CI should pass.
> chore: prepare for removal of deprecated method

- src/extensions/links.test.ts
- src/extensions/links.ts
- src/plugin.json
The Grafana Assistant is currently building the link to metrics drilldown manually in their code. This work adds a link from the metrics drilldown app to expose code to build the URL from our repo. 
This means that we are responsible for the correct building of the url.
https://github.com/user-attachments/assets/fbedf97c-de25-410e-98b5-8e38bafd7752
**Related issue(s):** https://github.com/grafana/metrics-drilldown/issues/501
Add an extension point link to build a URL for Grafana Assistant.
1. [Run Grafana Assistant locally](https://github.com/grafana/grafana-assistant-app) 
- Follow the steps exactly in the repo, please ask me if you get stuck 
2. Build metrics drilldown
3. Run Grafana locally from the instructions in the grafana assistant repository instructions (IMPORTANT)
4. Open the …
> feat(ExtensionPoint): Add link for Grafana assistant to build URL

- CHANGELOG.md
- package-lock.json
- package.json
As per the process described in the [Metrics Drilldown Deployment Handbook](https://wiki.grafana-ops.net/w/index.php?title=Engineering/Grafana/Grafana_Explore/Metrics_Drilldown/Deployment_Handbook#Recipe_for_engineers), this PR bumps the Metrics Drilldown app to v1.0.6.
> chore: bump version to v1.0.6

- docker-compose.yaml
**Related issue(s):** This PR closes #553 and aims to make e2e testing practical in https://github.com/grafana/metrics-drilldown/pull/446
This PR adds a new `grafana-scopes-gmd` service running on port `3002`. This Grafana server has feature toggles enabled that should make it possible to test Scopes x Metrics Drilldown functionality, such as in https://github.com/grafana/metrics-drilldown/pull/446.
`npm run server` now also creates a `grafana-scopes-gmd` container on port `3002`:
> ci: add Grafana instance with Scopes enabled

- src/RelatedMetricsScene/RelatedListControls.tsx
- src/WingmanDataTrail/ListControls/ListControls.tsx
- src/WingmanDataTrail/ListControls/QuickSearch/CountsProvider/CountsProvider.ts
- src/WingmanDataTrail/ListControls/QuickSearch/CountsProvider/MetricVariableCountsProvider.ts
- src/WingmanDataTrail/ListControls/QuickSearch/QuickSearch.tsx
**Related issue(s):** made to simplify https://github.com/grafana/metrics-drilldown/pull/557 
A refactor to decouple the [QuickSearch component](https://github.com/grafana/metrics-drilldown/blob/main/src/WingmanDataTrail/ListControls/QuickSearch/QuickSearch.tsx) from the metric variables. Indeed, prior to this PR, the search counts displayed in the UI were directly retrieved from the `MetricsVariable` and the `FilteredMetricsVariable` Scene objects.
This PR will enable us to reuse the `QuickSearch` component in  the "Breakdown" tab of the `MetricScene` and to display the number of labels.
We introduce the new `CountsProvider` class to be able to customize how counts are retrieved by `QuickSearch`.
See diff tab for specific comments.
> refactor(QuickSearch): Decouple QuickSearch from metric variables

- CHANGELOG.md
- package-lock.json
- package.json
This PR bumps the version to 1.0.7 as per the process described in the Metrics Drilldown [Deployment Handbook](https://wiki.grafana-ops.net/w/index.php?title=Engineering/Grafana/Grafana_Explore/Metrics_Drilldown/Deployment_Handbook#Recipe_for_engineers).
> chore: bump version v1.0.7

- src/DataTrail.tsx
- src/WingmanDataTrail/MetricsVariables/FilteredMetricsVariable.ts
This PR reduces the number of queries to fetch the list of all metrics **from 6 to 3**:
| <img width="1709" height="172" alt="Screenshot 2025-07-25 at 13 16 50" src="https://github.com/user-attachments/assets/0d1e1fe1-cd3d-4370-ac1f-666088578657" /> |  <img width="1710" height="107" alt="Screenshot 2025-07-25 at 13 18 03" src="https://github.com/user-attachments/assets/9515ed2a-efdf-4c44-bc79-52a3aa921d04" /> |
Prior to this PR, when landing on the page:
- `DataTrail` would render its component,
- during render, [histograms would be initialized](https://github.com/grafana/metrics-drilldown/blob/main/src/DataTrail.tsx#L310) by calling [MetricDatasourceHelper.initializeHistograms()](https://github.com/grafana/metrics-drilldown/b …
> perf(*): Prevent duplicated "metrics list" queries when landing on the page

- src/RelatedLogs/RelatedLogsScene.tsx
**Related issue(s):** fixes https://github.com/grafana/metrics-drilldown/issues/419
This PR adds a `<Spinner />` in the "Related logs" tab while loading the Loki datas sources. After they are loaded, it's not necessary to keep track of loading the logs because, once the data sources have been loaded, a Logs panel is rendered and logs start to be streamed to the UI.
- A spinner should appear while loading the Loki data sources
> feat(RelatedLogs): Add spinner while loading

- CHANGELOG.md
- package-lock.json
- package.json
✨ Description
This PR bumps the version to 1.0.8 from 1.0.7. We'll use the 1.0.8 tag as the basis for a new release.
📖 Summary of the changes
Changelog and package.json + lockfile updated as per https://wiki.grafana-ops.net/w/index.php/Engineering/Grafana/Grafana_Explore/Metrics_Drilldown/Deployment_Handbook#Versioning.
> chore: bump version to v1.0.8

- src/extensions/links.test.ts
- src/extensions/links.ts
- src/plugin.json
**Related issue(s):** 
Big issue: https://github.com/grafana/grafana-assistant-app/issues/956
[Grafana assistant PR](https://github.com/grafana/grafana-assistant-app/pull/1002)
1. Allow the grafana assistant extension point to use a full query to generate a URL
2. Generate a URL with only a datasource_uid and navigate to drillldown metrics reducer view.
1. Build the assistant
2. Ask the assistant to navigate to metrics drilldown with a query, metric or label filters.
3. The navigation should work.
> feat(Extensions): Update Grafana assistant extension point to use full query to generate a URL

- src/Breakdown/MetricLabelValuesList/MetricLabelsValuesList.tsx
- src/Breakdown/MetricLabelValuesList/SceneByFrameRepeater.tsx
**Related issue(s):** preparation to simplify the review on https://github.com/grafana/metrics-drilldown/pull/594
Before this PR any `$data` would have had to be attached to a parent of `SceneByFrameRepeater`, which in some cases, may not be convenient. This PR adds  a new  `$data` option to its constructor, as a convenience. 
See diff tab
> refactor(SceneByFrameRepeater): Allow $data to be passed to the constructor

- src/Breakdown/MetricLabelsList/LabelVizPanel.tsx
- src/services/sorting.ts
**Related issue(s):** fixes https://github.com/grafana/metrics-drilldown/issues/615
Two small changes:
1. We disable the "Select" button when there's no data
2. We improve the sorting code to prevent a runtime exception when the data frame is empty 
- Locally, after pulling this branch. See the linked issue for the reproduction steps.
> fix(MetricScene): Fix fatal error in an edge case where there's no data

- src/Breakdown/MetricLabelValuesList/LabelValueVizPanel.tsx
**Related issue(s):** is caused by https://github.com/grafana/metrics-drilldown/pull/608
After merging the linked PR, some warnings started to appear in the browser console, for instance:
This PR modifies `LabelValueVizPanel` so that it does not store any Scene object in its own state. By doing so, they can be used to build the timeseries panel (and attached only to it in the Scene graph).
- No warning messages related to Scene objects with multiple parents should appear in the browser's console
> fix(Breakdown): Address Scene warnings

- src/extensions/links.test.ts
- src/extensions/links.ts
**Related issue(s):** 
https://github.com/grafana/metrics-drilldown/issues/602
This interpolates Grafana template variables when navigating from a panel to metrics drilldown.
https://github.com/user-attachments/assets/947aa6f2-4374-4133-b6b2-f4ef5e605b14
1. We use the `templateSrv` to interpolate variables in the query and data source
2. Update types in the links.ts file 
3. Add Prometheus functions that are not exported from the prometheus package
1. Create a variable in a dashboard
2. Use a variable in a query in the dashboard (i.e. metrics or labels)
3. Exit edit mode in the dashboard and click the menu in the panel (three dots)
4. Open in metrics drilldown
5. See that the query is interpolated correctly
> fix(links): use template vars in links

- src/TrailStore/TrailStore.test.ts
- src/WingmanDataTrail/MetricsVariables/computeRulesGroups.ts
- src/autoQuery/behaviors/ExtremeValueFilterBehavior.tsx
- src/exposedComponents/LabelBreakdown/LabelBreakdown.tsx
- src/extensions/links.ts
- src/mocks/datasource.ts
- src/stubs/dataSourceStub.ts
- src/types/language-provider/v11-6-x.ts
- src/types/language-provider/v12-0-0.ts
- src/utils/utils.promql.ts
- src/utils/utils.timerange.ts
**Related issue(s):** This PR supports #625. It's purely a refactor PR, and it's job is to keep the "real PR" for #625 smaller and more focused.
- Our check for whether or not a metric is a recording rule is more robust. It's guided by the Prometheus best practices for rules naming as described in https://prometheus.io/docs/practices/rules/#naming.
- The `processLabelMatcher` utility has been moved to `utils/utils.promql`. In general, I think it'd be nice for `utils/utils.promql` to be the canonical place where the PromQL magic happens.
- Simplified handling of `SceneTimeRange` creation. The new `toSceneTimeRange` util makes it easier to deal with time ranges in our `exposedComponents`.
- The datasource stub is [correctly called a stub](https://stackoverflow.com/a/17810004/6387812), and …
> refactor: prepare for embedded metrics reducer

- src/App/useReportAppInitialized.ts
- src/interactions.ts
Capture the uel_epid param which is the extension point id.
This can indicate if the app was opened from our targets in plugin.json and future extension points.
```
"grafana/dashboard/panel/menu",
"grafana/explore/toolbar/action",
"grafana-assistant-app/navigateToDrilldown/v1",
"grafana/alerting/alertingrule/queryeditor"
```
The build passes.
Check the `app_initialized` event after this is merged to see the uel_epid captured.
> chore: capture extension point id for initializing app

- src/DataTrail.tsx
- src/GmdVizPanel/GmdVizPanel.tsx
- src/RelatedMetricsScene/RelatedMetricsScene.tsx
- src/WingmanDataTrail/MetricsReducer.tsx
- src/helpers/MetricDatasourceHelper.ts
- src/mocks/datasource.ts
**Related issue(s):** follow-up of https://github.com/grafana/metrics-drilldown/pull/645
This PR aims at improving how the app determines if a metric is a native histogram or not. It achieves it by removing the extra request made to fetch all the metrics in favour of listening to the `MetricsVariable` changes. 
The strategy works well in the `MetricsReducer` because, anyway, the app needs the options of `MetricsVariable` to be able to render the metrics list.
When the user lands directly on the `MetricScene`, there's some extra loading time as the app now has to wait for `MetricsVariable` to load its options. The "reward" is that, for native histograms,  the main viz will directly render the correct panel type.
To make things work:
1. `MetricsVariable` has been moved to `DataTrail` so it …
> perf(*): Improve Native Histograms detection

- jest.config.js
- src/App/App.tsx
- src/Breakdown/MetricLabelValuesList/SortBySelector.tsx
- src/GmdVizPanel/components/ConfigurePanelAction.tsx
- src/GmdVizPanel/components/ConfigurePanelForm/ConfigurePanelForm.tsx
- src/GmdVizPanel/config/getPreferredConfigForMetric.ts
- src/MetricsDrilldownDataSourceVariable.ts
- src/TrailStore/TrailStore.test.ts
- src/TrailStore/TrailStore.ts
- src/UserPreferences/userStorage.ts
- src/WingmanDataTrail/ListControls/MetricsSorter/MetricsSorter.test.tsx
- src/WingmanDataTrail/ListControls/MetricsSorter/MetricsSorter.tsx
- src/interactions.ts
- src/mocks/userStorage.ts
**Related issue(s):** is a follow-up of https://github.com/grafana/metrics-drilldown/pull/618
The linked PR introduced a `UserPreferences` class, which was incorrectly named.
Just renaming `UserPreferences` to `UserStorage`.
> refactor(UserPreferences): Rename to UserStorage

- src/DataTrail.tsx
- src/GmdVizPanel/__test__/buildQueryExpression.spec.ts
- src/GmdVizPanel/buildQueryExpression.ts
- src/GmdVizPanel/types/heatmap/__test__/getHeatmapQueryRunnerParams.spec.ts
- src/GmdVizPanel/types/percentiles/__test__/getPercentilesQueryRunnerParams.spec.ts
- src/GmdVizPanel/types/stat/__test__/getStatQueryRunnerParams.spec.ts
- src/GmdVizPanel/types/statushistory/__test__/getStatushistoryQueryRunnerParams.spec.ts
- src/GmdVizPanel/types/timeseries/__test__/getTimeseriesQueryRunnerParams.spec.ts
**Related issue(s):** follow-up of https://github.com/grafana/metrics-drilldown/pull/623
The linked PR was a quick hack to prevent incorrect queries to be made when some label values contained the equal sign.
This PR solves completely the problem.
We use the [`:raw` variable formatter](https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax/#raw) and let Scenes interpolate and escape the value for us.
> fix(*): Fix queries for label values containing special chars (like the equal sign)

- src/MetricGraphScene.tsx
- src/WingmanDataTrail/MetricsReducer.tsx
This PR to prevent flicker in the `MetricsReducer` (the list was rendered twice in a row) and the `MetricScene` (the action bar was missing when landing on the page and it would then appear):
|  https://github.com/user-attachments/assets/abe7d574-70dd-42cf-93a8-4687bd551b09 | https://github.com/user-attachments/assets/c7f61298-aa50-48ff-8f25-2bcbac429092 |
See diff tab
`-`
> fix(*): Prevent flickering

- src/Breakdown/MetricLabelValuesList/AddToFiltersGraphAction.tsx
- src/DataTrail.test.tsx
- src/DataTrail.tsx
- src/MetricScene.tsx
- src/bookmarks/genBookmarkKey.ts
- src/utils.test.ts
- src/utils.ts
A cleanup PR, where unused `DataTrail` class variables are removed:
- `nativeHistogramMetric`,
- `metricSearch ` and
- `trailActivated`
...as well as their related code.
Additionally, the naming and the organization of the code in the class have been improved. For instance, check `onActivate` now.
See specific comments in the diff tab.
> refactor(*): Cleanup unused variables + related refactorings

- e2e/tests/metric-scene-view.spec.ts
- src/RelatedLogs/RelatedLogsScene.tsx
Just a quick fix when the user goes to the `MetricScene`, clicks on the "Related logs" tab and no logs are found:
A call to `sceneGraph.findByKeyAndType` with the wrong type of object was causing a runtime error.
- A simple E2E test has been added in this PR ; the build should pass
**Note:** in the near future, we should setup and start testing with a Loki data source
> fix(RelatedLogs): Fix fatal error when no logs are found

- src/DataTrail.tsx
- src/GmdVizPanel/GmdVizPanel.tsx
- src/GmdVizPanel/components/ConfigurePanelForm/ConfigurePanelForm.tsx
- src/GmdVizPanel/config/presets/getConfigPresetsForMetric.ts
- src/GmdVizPanel/matchers/__tests__/isCounterMetric.test.ts
- src/GmdVizPanel/matchers/__tests__/isStatusUpDownMetric.test.ts
- src/GmdVizPanel/matchers/getMetricType.ts
- src/GmdVizPanel/matchers/getPanelTypeForMetric.ts
- src/GmdVizPanel/matchers/isClassicHistogramMetric.ts
- src/GmdVizPanel/matchers/isCounterMetric.ts
- src/GmdVizPanel/matchers/isHistogramMetric.ts
- src/GmdVizPanel/matchers/isStatusUpDownMetric.ts
- src/MetricGraphScene.tsx
- src/helpers/MetricDatasourceHelper.ts
This PR decreases the time to first render of the `GmdVizPanel` by determing if the metric is a native histogram or not **after** rendering the component. Indeed it's an async process that may require a call to the backend API.
Locally, some tests have shown a decrease of 100ms between the activation of the Scene object and the 1st render of the component.
Additionally:
1. prior to this PR, the metric type that was tracked when the user opened the config Prometheus form did not take into consideration if the metric was a native histogram or not. The same was happening when the config was applied or restored,
2. this PR adds matchers in `src/GmdVizPanel/matchers`: `getPanelTypeForMetric` and `getPanelTypeForMetricSync`
3. and this PR also adds some missing unit …
> perf(GmdVizPanel): Faster first render + small refatorings

- src/Breakdown/GroupByVariable.tsx
**Related issue(s):** relates to https://github.com/grafana/metrics-drilldown/pull/652
https://github.com/grafana/metrics-drilldown/pull/652 introduced the filtering for "le" labels in the "Breakdown" tab but a small bug was also introduced. This PR fixes it.
See diff tab
- The build should pass and the "le" label should never show up for classic histograms.
> fix(Breakdown): Remove "le label from options

- src/utils.ts
**Related issue(s):** relates to https://github.com/grafana/metrics-drilldown/issues/426
The support for namespacing URL search parameters was added to Scenes in https://github.com/grafana/scenes/pull/1156 but Metrics Drilldown is not using it, so its variables might collide with other variables when the app is embedded. 
See diff tab
`-`
> fix(DataTrail): Set URL search parameters namespace when the app/components are embedded

- docker-compose.yaml
Regenerating screenshots was failing due to not being able to find the grafana version due to a little bug.
No conflicting version in docker compose yaml.
Run screenshot gen script. `./scripts/e2e-gen-all-screenshots.sh `
build passes
> fix(Docker): Fix GRAFANA_IMAGE env var used in playwright

- e2e/config/playwright.config.common.ts
Seems like `process.env.GRAFANA_VERSION` is now needed to run playwright tests. However in local development running the base `docker-compose` that env might not be set which causes failures.
This helps address that and give better DX
> chore: fallback grafana version in playwright screenshots

- CHANGELOG.md
- package-lock.json
- package.json
This PR correctly bumps the version to 1.0.14 to prepare the next release. It follows the **Versioning** steps described in the Metrics Drilldown [Deployment Handbook](https://wiki.grafana-ops.net/w/index.php/Engineering/Grafana/Grafana_Explore/Metrics_Drilldown/Deployment_Handbook#Recipe_for_engineers).
> chore: bump version v1.0.14 correctly

- src/AppDataTrail/DataTrail.tsx
- src/AppDataTrail/MetricDatasourceHelper/MetricDatasourceHelper.ts
This PR ensures that the cache metadata is _always_ cleared when the data source changes.
The previous code relied on subscribing to `MetricsDrilldownDataSourceVariable` state changes but weirdly, when (e.g.) going to the `MetricScene`, coming back to `MetricsReducer` and then changing the data source, the subscriber function would not be called 🤷🏾‍♂️.
Instead of subscribing to `MetricsDrilldownDataSourceVariable` state changes, this PR relies on the Scenes variable dependency.
Manually, after checking out this PR's branch, by looking at the network tab to see:
- that the new metadata is fetched _once_ when landing
- that the new metadata is properly refetched when changing data source
> fix(MetricDatasourceHelper): Fix cache refresh when changing data source

- .github/workflows/cd.yml
This is needed to get CD working properly with `ops` and `dev` building from `main`
> chore: add git ref sha in CD
